name: wakelock
description: >-2
  Plugin that allows you to keep the device screen awake, i.e. prevent the screen from sleeping on
  Android, iOS, macOS, Windows, and web.
version: 0.7.0
repository: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock
publish_to: none


environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.9.1

  wakelock_platform_interface: 
    git:
      url: git@github.com:grisoftware/wakelock.git
      ref: main
      path: wakelock_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  pigeon: ^10.0.0 # flutter pub run pigeon --input "pigeons/messages.dart"

flutter:
  plugin:
    platforms:
      android:
        package: creativemaybeno.wakelock
        pluginClass: WakelockPlugin
      ios:
        pluginClass: WakelockPlugin
